SecureApiGateway/secure-api-gateway-ob-uk-functional-tests

Dockerfile

New docker container for running securebanking functional tests
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/7

add Dockerfile for new functional tests

---

.github/workflows/master.yml
.github/workflows/pr.yml

Add github actions for creating the docker container
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/7

add ci for the functional test image

---

_infra/kubernetes/job.yaml
codefresh.yml

Add a codefresh pipeline for easy testing.
Add delete policy to the helm chart for argo.
https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/7

add hook delete

---

.github/workflows/master.yml
.github/workflows/pr.yml
.gitignore

Run tests against a users environment when a PR is raised.
issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89

run tests on pr

---

src/test/kotlin/com/forgerock/securebanking/support/account/AccountRS.kt
src/test/kotlin/com/forgerock/securebanking/tests/functional/account/parties/GetAccountPartyTest.kt
src/test/kotlin/com/forgerock/securebanking/tests/functional/account/parties/GetPartyTest.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/228

228: Fix party requests in the functional tests

---

src/test/kotlin/com/forgerock/securebanking/framework/data/DynamicRegistration.kt
src/test/kotlin/com/forgerock/securebanking/framework/data/ManualRegistration.kt
src/test/kotlin/com/forgerock/securebanking/framework/data/RequestParameters.kt
src/test/kotlin/com/forgerock/securebanking/framework/signature/SignatureUtils.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/account/AccountAS.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/event/EventsDataFactory.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentAS.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentRS.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/CreateDomesticPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/GetDomesticPaymentDomesticPaymentIdPaymentDetailsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/GetDomesticPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/CreateDomesticPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/GetDomesticPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/GetDomesticPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/CreateDomesticScheduledPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/GetDomesticScheduledPaymentDomesticPaymentIdPaymentDetailsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/GetDomesticScheduledPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/CreateDomesticScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/GetDomesticScheduledPaymentsConsentsTest.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/346

346: Reorganize the classes in securebanking-openbanking-uk-common

---

src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentFactory.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/CreateDomesticStandingOrderTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/GetDomesticStandingOrderDomesticStandingOrderIdPaymentDetailsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/GetDomesticStandingOrderTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/GetDomesticStandingOrderConsentsTest.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/334

334: Create functional tests coverage: submit domestic standing order

---

src/test/kotlin/com/forgerock/securebanking/framework/http/fuel/FuelInitialiser.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentFactory.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentRS.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/CreateInternationalPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/GetInternationalPaymentInternationalPaymentIdPaymentDetailsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/GetInternationalPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/CreateInternationalPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/GetInternationalPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/GetInternationalPaymentsConsentsTest.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/373

373: Create functional tests coverage: submit International payment

---

build.gradle.kts
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/CreateInternationalScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/GetInternationalScheduledPaymentsConsentsTest.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/417

417: international scheduled payment consent

---

src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentFactory.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/CreateInternationalScheduledPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/GetInternationalScheduledPaymentInternationalScheduledPaymentIdPaymentDetailsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/GetInternationalScheduledPaymentTest.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/418

418: Submit international scheduled payment

---

src/test/kotlin/com/forgerock/uk/openbanking/framework/errors/Errors.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/CreateDomesticScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/CreateInternationalScheduledPaymentsConsentsTest.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/425

425: RequestExecutionDate in the past tests

---

src/test/kotlin/com/forgerock/securebanking/framework/http/fuel/FuelInitialiser.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/483

483: Remove the BigDecimalSerializer

---

src/test/kotlin/com/forgerock/uk/openbanking/readme.md

Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/487

487: Updating the readme to document how tests are organised post refactoring

---

gradle/profiles/profile-default.gradle.kts

- Updated dev profile to use the new eidas signing kid
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/493

493 update expired ob certs

---

src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentAS.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentApiClient.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/legacy/LegacyCreateDomesticPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/legacy/LegacyCreateDomesticScheduledPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/legacy/LegacyCreateDomesticStandingOrderTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/api/v3_1_8/CreateInternationalPaymentsConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/api/v3_1_8/GetInternationalPaymentsConsentFundsConfirmation.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_8/GetInternationalPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_9/GetInternationalPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/legacy/LegacyCreateInternationalPaymentTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/api/v3_1_8/CreateInternationalScheduledPayment.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/api/v3_1_8/CreateInternationalScheduledPaymentsConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/api/v3_1_8/GetInternationalScheduledPaymentsConsentFundsConfirmation.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_8/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_9/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/legacy/LegacyGetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/legacy/LegacyCreateInternationalScheduledPaymentTest.kt

Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/436

436: Update functional tests after calculate elements

---

codefresh.yml

https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/511

511: Adding NOTIFY_SLACK pipeline variable to allow slack notifications to be enabled/disabled on a per run basis

---

src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_10/GetDomesticPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_9/GetDomesticPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_10/GetInternationalPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_8/GetInternationalPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_9/GetInternationalPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/legacy/LegacyGetInternationalPaymentsConsentFundsConfirmationTest.kt

- International payments funds confirmation coverage
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/380

380: international payments funds confirmation

---

src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_10/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_8/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_9/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/legacy/LegacyGetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt

- International scheduled payment funds confirmation coverage
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/419

419: International scheduled payment funds confirmation

---

src/test/kotlin/com/forgerock/securebanking/framework/data/Tpp.kt

https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/620

620: Setting DCR RegistrationRequest.iss to the SSA software_id

---

.gitignore
gradle/profiles/profile-default.gradle.kts
gradle/profiles/profile-devops.gradle.kts
gradle/profiles/profile-nightly.gradle.kts

Was going to use a env var to change the two values that differ between the profiles, but for the time being its quicker and less changes to add in new profile files
This way the existing PROFILE CF variable can be altered to differ what profile file to use
issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/536

536 - Functional Tests for devops and nightly environment

---

.github/workflows/pr.yml

With the rename of the codefresh pipelines for different environment we need to update any references to pipelines calls to the new names 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/737

737 - Change to dev-functional-test reference 

---

src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/api/v3_1_10/GetDomesticVrpConsentsFundsConfirmation.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/junit/v3_1_10/GetDomesticVrpConsentsFundsConfirmationTest.kt

Issue: https://github.com/secureapigateway/secureapigateway/issues/650
Description: Added domestic vrp consents funds confirmation functional tests.

650: Adding domestic vrp consents funds confirmation functional tests

---

src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentFactory.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/api/v3_1_10/GetDomesticVrp.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/api/v3_1_10/GetDomesticVrpDetails.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/junit/v3_1_10/CreateDomesticVrpTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/junit/v3_1_10/GetDomesticVrpDetailsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/junit/v3_1_10/GetDomesticVrpTest.kt

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/651
Implemented functional tests for Domestic VRPs submit payment, get payment and get payment details APIs.

Submit, Get and get details tests for domestic vrps

---

src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/api/v3_1_10/GetDomesticVrpConsentsFundsConfirmation.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/junit/v3_1_10/GetDomesticVrpConsentsFundsConfirmationTest.kt

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/650
Description: Replaced domestic vrp consents funds confirmation endpoint.

650: Replacing domestic vrp consents funds confirmation endpoint

---

build.gradle.kts

- Updated dependency uk bom
Issue: https://github.com/secureapigateway/secureapigateway/issues/731

731: debtor account optional, uk bom version updated

---

build.gradle.kts
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/api/v3_1_8/CreateDomesticPaymentsConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_10/CreateDomesticPaymentConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_8/CreateDomesticPaymentConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_9/CreateDomesticPaymentConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/api/v3_1_8/CreateDomesticScheduledPaymentsConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/junit/v3_1_10/CreateDomesticScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/junit/v3_1_8/CreateDomesticScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/junit/v3_1_9/CreateDomesticScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/api/v3_1_8/CreateDomesticStandingOrderConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/junit/v3_1_10/CreateDomesticStandingOrderConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/junit/v3_1_8/CreateDomesticStandingOrderConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/junit/v3_1_9/CreateDomesticStandingOrderConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/api/v3_1_10/CreateDomesticVrpConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/api/v3_1_10/GetDomesticVrpConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/junit/v3_1_10/CreateDomesticVrpConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/api/v3_1_8/CreateInternationalPaymentsConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_10/CreateInternationalPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_8/CreateInternationalPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_9/CreateInternationalPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/api/v3_1_8/CreateInternationalScheduledPaymentsConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_10/CreateInternationalScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_8/CreateInternationalScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_9/CreateInternationalScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/standing/orders/consents/api/v3_1_8/CreateInternationalStandingOrderConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/standing/orders/consents/junit/v3_1_10/CreateInternationalStandingOrderConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/standing/orders/consents/junit/v3_1_8/CreateInternationalStandingOrderConsentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/standing/orders/consents/junit/v3_1_9/CreateInternationalStandingOrderConsentsTest.kt

- Added test for optional debtor account for all payment initiation
Issue: https://github.com/secureapigateway/secureapigateway/issues/731

731: optional debtor account

---

src/test/kotlin/com/forgerock/uk/openbanking/support/account/AccountAS.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/general/GeneralAS.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentAS.kt

To be compatible with rcs change: https://github.com/SecureApiGateway/securebanking-openbanking-uk-rcs/pull/87
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/805

805: Update RCS request paths

---

src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentApiClient.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/api/v3_1_10/CreateDomesticVrpConsents.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/consents/junit/v3_1_10/CreateDomesticVrpConsentsTest.kt

- Added coverage to vrp consent deletion 
Issue: https://github.com/secureapigateway/secureapigateway/issues/824

824: delete vrp consent

---

gradle/profiles/profile-devops.gradle.kts
gradle/profiles/profile-nightly.gradle.kts

https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/839

839: Fixing igServer address in nightly and devops profiles

---

gradle/profiles/profile-dev.gradle.kts
gradle/profiles/profile-devops.gradle.kts
gradle/profiles/profile-nightly.gradle.kts
src/test/kotlin/com/forgerock/securebanking/framework/configuration/Config.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/accounts/api/v3_1_8/GetAccount.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/accounts/legacy/LegacyGetAccountTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/balances/api/v3_1_8/GetAccountBalances.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/balances/legacy/LegacyGetAccountBalancesTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/beneficiaries/api/v3_1_8/GetAccountBeneficiaries.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/beneficiaries/legacy/LegacyGetAccountBeneficiariesTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/direct/debits/api/v3_1_8/GetAccountDirectDebits.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/direct/debits/legacy/LegacyGetAccountDirectDebitsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/offers/api/v3_1_8/GetAccountOffers.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/offers/legacy/LegacyGetAccountOffersTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/parties/api/v3_1_8/GetAccountParties.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/parties/legacy/LegacyGetAccountPartiesTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/products/api/v3_1_8/GetAccountProduct.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/products/legacy/LegacyGetAccountProductTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/scheduled/payments/api/v3_1_8/GetAccountScheduledPayments.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/scheduled/payments/legacy/LegacyGetAccountScheduledPaymentsTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/standing/orders/api/v3_1_8/GetAccountStandingOrders.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/standing/orders/legacy/LegacyGetAccountStandingOrdersTest.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/transactions/api/v3_1_8/GetAccountTransactions.kt
src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/transactions/legacy/LegacyGetAccountTransactionsTest.kt

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/490
Added static account id

Adding static account id instead of making a request every time.

---

src/test/kotlin/com/forgerock/securebanking/framework/data/DynamicRegistration.kt
src/test/kotlin/com/forgerock/securebanking/framework/signature/SignatureUtils.kt

Issue: https://github.com/secureapigateway/secureapigateway/issues/733

733: Make tests pass after refactor of ProcessRegistration.groovy

---

src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/account/AccountRS.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/PaymentApiClient.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/PaymentRS.kt

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/817
Removed x-fapi-financial-id header

817: Removed x-fapi-financial-id header

---

.github/dependabot.yml

Issue: https://github.com/secureapigateway/secureapigateway/issues/889

889: Enable dependabot version PRs

---

build.gradle.kts
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/legacy/LegacyCreateInternationalPaymentTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v3_1_8/CreateInternationalScheduledPayment.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/legacy/LegacyCreateInternationalScheduledPaymentTest.kt

- Bumped commons release 1.0.4
- Fix exchangRate assertions in international payments
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/981

981 fix file payment error bigDecimal equality

---

build.gradle.kts

- Updated build gradle project version and release to 1.0.3
Issue: https://github.com/secureapigateway/secureapigateway/issues/995

995 prepare release 1.0.2

---

src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/errors/Errors.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/CreateDomesticScheduledPayment.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/GetDomesticScheduledPayment.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/consents/api/v3_1_8/CreateDomesticScheduledPaymentsConsents.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/consents/junit/v3_1_10/CreateDomesticScheduledPaymentsConsentsTest.kt

https://github.com/SecureApiGateway/SecureApiGateway/issues/1060

1060: Fixing tests to work with RS implementation of Domestic Scheduled Payment Consent API

---

src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/api/v3_1_8/CreateDomesticStandingOrder.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/api/v3_1_8/GetDomesticStandingOrder.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/consents/api/v3_1_8/CreateDomesticStandingOrderConsents.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/consents/junit/v3_1_10/CreateDomesticStandingOrderConsentsTest.kt

https://github.com/SecureApiGateway/SecureApiGateway/issues/1061

1061: Fixing tests to work with RS implementation of Domestic Standing Order Consent API

---

src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/api/v3_1_8/GetInternationalPayment.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/api/v3_1_8/CreateInternationalPaymentsConsents.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/junit/v3_1_10/CreateInternationalPaymentsConsentsTest.kt

https://github.com/SecureApiGateway/SecureApiGateway/issues/1062

1062: Fixing tests to work with RS/RCS impl on Consent API for International Payments

---

src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/api/v3_1_8/CreateInternationalStandingOrder.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/api/v3_1_8/GetInternationalStandingOrder.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/consents/api/v3_1_8/CreateInternationalStandingOrderConsents.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/consents/junit/v3_1_10/CreateInternationalStandingOrderConsentsTest.kt

https://github.com/SecureApiGateway/SecureApiGateway/issues/1064

1064: Fixing tests to work with RS/RCS impl on Consent API for International Standing Orders

---

src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt

https://github.com/SecureApiGateway/SecureApiGateway/issues/1053

1053: Updating VRPType validation error message assertion

---

gradle/profiles/profile-dev.gradle.kts
gradle/profiles/profile-devops.gradle.kts
gradle/profiles/profile-fritss-itssdev.gradle.kts
gradle/profiles/profile-nightly.gradle.kts
gradle/profiles/profile-ob-sandbox-v1.gradle.kts
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/configuration/Config.kt

New Software Id: Y6NjA9TOn3aMm9GaPtLwkp
New Signing Key Id: qfL4CT5GrVgoyXNQtUjF5TIVOXA
https://github.com/SecureApiGateway/SecureApiGateway/issues/1094

1094: Configuring test profiles to use new SAPI-G Automated Testing TPP

---

README.md

https://github.com/SecureApiGateway/SecureApiGateway/issues/1094

1094: Update link to certificates in README.md

---

build.gradle.kts
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/discovery/RsDiscovery.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/funds/FundsConfirmationAS.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/funds/FundsConfirmationConsentFactory.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/funds/FundsConfirmationFactory.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/funds/FundsConfirmationRS.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/funds/api/v3_1_10/FundsConfirmations.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/funds/consents/api/v3_1_10/FundsConfirmationConsents.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/funds/consents/junit/v3_1_10/FundsConfirmationConsentTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/funds/junit/v3_1_10/FundsConfirmationsTest.kt

- Added coverage for funds confirmation API
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/611

611: funds confirmation functional test coverage

---

build.gradle.kts

- Upgrade version to 2.0.0
- Bumped commons version 2.0.0
Issue: https://github.com/SecureApiGateway/fr-platform-config

1099: prepare for the release 2.0.0

---

build.gradle.kts

Need to create a new version to have new profile included
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099

1099: Up version to 2.0.1

---

build.gradle.kts
gradle/profiles/profile-ob-sandbox-v2.gradle.kts

Updated platformServer & amcookie
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1099

1099: Fixes for v2.0.0 & bump to 2.0.2

---

build.gradle.kts

Artifactory has moved and the URL has changed. See the following backstage article;
https://backstage.forgerock.com/knowledge/kb/article/a53108595
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1167

1167: Fix Funcitonal Tests builds

---

build.gradle.kts

Bump Versions and common bom
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251

1251: Prepare 230 release

---

.github/workflows/release.yml

Vars are used for the artifact registry repo now not secrets
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1251

1251: Fix release workflow

---

.github/workflows/master.yml
.github/workflows/pr.yml
.github/workflows/release.yml

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1264

1264: Update actions that have deprecations

---

gradle/profiles/profile-nightly.gradle.kts

Change Cookie for new nightly instance
https://github.com/SecureApiGateway/SecureApiGateway/issues/1288

1288: Changes to cloud instance config for pushing to cloud tenant

---

.github/workflows/pr.yml
Makefile
README.md

Update the pipeline location for new codefresh instance 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1327

1327: Migrate Codefresh Instances

---

.github/workflows/release.yml

The docker command was tagging as  securebanking/tests/uk-func... but only pushing tags from securebanking/uk-func...
Remove the tests from the path as not wanted 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1361

1361: Investigate Issue with Functional Tests version not being tagged in docker image

---

.github/workflows/release.yml
Makefile

Amend release workflow to use reusable CI repo workflow
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389

1389: Use CI Repo for standardised steps in github workflows

---

build.gradle.kts

Update version & Common to version 3.0.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1404

1404: Create and Release SAPIG Core and OB

---

build.gradle.kts

Bump version to 3.0.1
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1460

1460: Create and Deploy Release 3.0.1

---

build.gradle.kts

Update version and common to `3.1.0`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1476

1476: Build and Deploy SAPIG 3.1.0 to relenv

---

build.gradle.kts

Bump common and func test version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1516

1516: Create release 3.2.0 and deploy

---

build.gradle.kts
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/DefaultOBDomesticVRPConsentRequestFactory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/DefaultOBWriteDomesticConsent4Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/DefaultOBWriteDomesticScheduledConsent4Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/DefaultOBWriteDomesticStandingOrderConsent5Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/DefaultOBWriteInternationalConsent5Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/DefaultOBWriteInternationalScheduledConsent5Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/DefaultOBWriteInternationalStandingOrderConsent6Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/PaymentFactory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/GetDomesticPaymentDetails.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v3_1_8/GetDomesticPaymentsConsentFundsConfirmation.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v3_1_8/GetDomesticPaymentsConsents.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/GetDomesticScheduledPaymentDetails.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/consents/api/v3_1_8/GetDomesticScheduledPaymentsConsents.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt

Issue https://github.com/SecureApiGateway/SecureApiGateway/issues/1560
Fixed imports after splitting detamodel in v3 and v4 packages

Tests refactor

---

build.gradle.kts
src/main/kotlin/com/forgerock/sapi/gateway/framework/conditions/ConditionStatus.kt
src/main/kotlin/com/forgerock/sapi/gateway/framework/configuration/Config.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/ConsentFactoryRegistryHolder.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/v4/DefaultOBWriteDomesticConsent4Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/v4/OBWriteDomesticConsent4Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/errors/Errors.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/v4/PaymentFactory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v4_0_0/CreateDomesticPayment.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v4_0_0/GetDomesticPayment.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v4_0_0/GetDomesticPaymentDetails.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v4_0_0/CreateDomesticPaymentsConsents.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v4_0_0/GetDomesticPaymentsConsentFundsConfirmation.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v4_0_0/GetDomesticPaymentsConsents.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/junit/v4_0_0/CreateDomesticPaymentConsentsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/junit/v4_0_0/GetDomesticPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/junit/v4_0_0/GetDomesticPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/junit/v4_0_0/CreateDomesticPaymentTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/junit/v4_0_0/GetDomesticPaymentDetailsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/junit/v4_0_0/GetDomesticPaymentTest.kt

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1564
- Refactored test support package names from commons library
- Added domestic payments v4 functional tests

Tests for Domestic Payments V4

---

build.gradle.kts
src/main/kotlin/com/forgerock/sapi/gateway/framework/configuration/Config.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/ConsentFactoryRegistryHolder.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/v4/DefaultOBDomesticVRPConsentRequestFactory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/v4/OBDomesticVRPConsentRequestFactory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v4_0_0/CreateDomesticVrp.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v4_0_0/GetDomesticVrp.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v4_0_0/GetDomesticVrpDetails.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/api/v4_0_0/CreateDomesticVrpConsents.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/api/v4_0_0/CreateDomesticVrpConsentsFundsConfirmation.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/api/v4_0_0/GetDomesticVrpConsents.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/junit/v4_0_0/CreateDomesticVrpConsentsFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/junit/v4_0_0/CreateDomesticVrpConsentsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/junit/v4_0_0/GetDomesticVrpConsentsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v4_0_0/CreateDomesticVrpTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v4_0_0/GetDomesticVrpDetailsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v4_0_0/GetDomesticVrpTest.kt

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1573
Implemented functional tests for domestic VRPs

Domestic VRP tests

---

src/main/kotlin/com/forgerock/sapi/gateway/framework/configuration/Config.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/ConsentFactoryRegistryHolder.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/v4/DefaultOBWriteInternationalScheduledConsent5Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/consent/payment/v4/OBWriteInternationalScheduledConsent5Factory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/v4/PaymentFactory.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v4_0_0/CreateInternationalScheduledPayment.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v4_0_0/GetInternationalScheduledPayment.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v4_0_0/GetInternationalScheduledPaymentDetails.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/api/v4_0_0/CreateInternationalScheduledPaymentsConsents.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/api/v4_0_0/GetInternationalScheduledPaymentsConsentFundsConfirmation.kt
src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/api/v4_0_0/GetInternationalScheduledPaymentsConsents.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/junit/v4_0_0/CreateInternationalScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/junit/v4_0_0/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/junit/v4_0_0/GetInternationalScheduledPaymentsConsentsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/junit/v4_0_0/CreateInternationalScheduledPaymentTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/junit/v4_0_0/GetInternationalScheduledPaymentDetailsTest.kt
src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/junit/v4_0_0/GetInternationalScheduledPaymentTest.kt

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1592
Added international scheduled payments tests.

International Scheduled Payments tests

---

build.gradle.kts

Bump common
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1602

1602: Build and Deploy SAPIG 4.0.0

---

.gitignore
Makefile
build.gradle.kts
gradle/profiles/profile-dev-aic-ob.gradle.kts
gradle/profiles/profile-dev-cdk-ob.gradle.kts

Update profile names
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1590

1590 Rename environment

---

build.gradle.kts

Bump version and common
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1625

1625: SAPIG Release 4.0.3 - Further OB V4 Support

---

build.gradle.kts

Bump common to 4.0.4-SNAPSHOT
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1626

1626: Prepare repos for Post 4.0.3

---

build.gradle.kts

Bump version to `4.0.4 `
Revert common to `4.0.0`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1642

1642: Create SAPIG 4.0.4

---

Makefile
gradle/profiles/profile-dev-aic-ob.gradle.kts
gradle/profiles/profile-dev-cdk-ob.gradle.kts
gradle/profiles/profile-devops-ob.gradle.kts
gradle/profiles/profile-ob-sandbox-v1.gradle.kts
gradle/profiles/profile-ob-sandbox-v2.gradle.kts
gradle/profiles/profile-ob-sandbox-v3.gradle.kts
gradle/profiles/profile-ob-sandbox-v4.gradle.kts
gradle/profiles/profile-ob-sandbox-v5.gradle.kts
gradle/profiles/profile-openig-nightly-ob.gradle.kts
src/main/kotlin/com/forgerock/sapi/gateway/framework/configuration/Config.kt

Update OBWac and OBSeal KID for new certs
Issue: https://pingidentity.atlassian.net/jira/software/c/projects/OPENIG/boards/1322?selectedIssue=OPENIG-9694

Openig 9694: Create new TPP OB Certificate for Automated Testing
