SecureApiGateway/secure-api-gateway-ob-uk-functional-tests

- Dockerfile
- _infra/kubernetes/job.yaml
Add a kubernetes manifest for deploying the functional tests into kubernetes and ensure that the compile target is executed at the `RUN` docker phase.
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/7
> add kubernetes job for functional tests

- src/test/kotlin/com/forgerock/securebanking/support/account/AccountRS.kt
- src/test/kotlin/com/forgerock/securebanking/tests/functional/account/parties/GetAccountPartiesTest.kt
- src/test/kotlin/com/forgerock/securebanking/tests/functional/account/parties/GetAccountPartyTest.kt
- src/test/kotlin/com/forgerock/securebanking/tests/functional/account/parties/GetPartyTest.kt
- Deleted the userid for party tests
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/240
> 240: AISP evaluation policy for party api

- build.gradle.kts
- src/test/kotlin/com/forgerock/securebanking/framework/http/fuel/FuelInitialiser.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentAS.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentFactory.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/GetDomesticPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/CreateDomesticScheduledPaymentTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/GetDomesticScheduledPaymentDomesticPaymentIdPaymentDetailsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/GetDomesticScheduledPaymentTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/CreateDomesticScheduledPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/GetDomesticScheduledPaymentsConsentsTest.kt
Issues: 
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/286
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/287
- Enable the tests for Get Domestic Payment Details and Get Domestic Scheduled Payment Details
- Enable the tests for the Domestic Payments Fund Confirmation
I have created issues for the disabled tests:
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/337
- https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/336
> 286, 287: Functional tests for Domestic Scheduled payments

- build.gradle.kts
- src/test/kotlin/com/forgerock/uk/openbanking/support/account/AccountAS.kt
- Fix the field to submit the consent decision
- Fix tests_$VERSION, rollback dependsOn to use filter{}
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/237
> 237: sharedAccounts field to accountIds direct mapping

- build.gradle.kts
- src/test/kotlin/com/forgerock/uk/openbanking/framework/constants/Constants.kt
- src/test/kotlin/com/forgerock/uk/openbanking/framework/errors/Errors.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentRS.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/CreateDomesticStandingOrderConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/GetDomesticStandingOrderConsentsTest.kt
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/333
> 333: Create functional tests coverage for domestic standing order consent

- .github/workflows/pr.yml
- build.gradle.kts
Setting apiVersions configuration to support v3_1_8 and v3_1_9
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/440
> 440: Support adding gradle tasks for multiple OBIE API versions

- codefresh.yml
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/440
> 440: Updating the CF pipeline to enable multiple versions to be passed as a string

- build.gradle.kts
Update to the latest version of Kotlin, the version we currently use is deprecated and doesn't work out of the box with the latest Intellij 
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/504
> 504: Update Kotlin to 1.7.10

- src/test/kotlin/com/forgerock/uk/openbanking/framework/errors/Errors.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/general/GeneralAS.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/api/v3_1_8/CreateDomesticPayment.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/api/v3_1_8/CreateDomesticPaymentsConsents.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/api/v3_1_8/GetDomesticPaymentsConsentFundsConfirmation.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_8/CreateDomesticPaymentConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_8/GetDomesticPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_9/CreateDomesticPaymentConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_9/GetDomesticPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/api/v3_1_8/CreateDomesticScheduledPaymentsConsents.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/junit/v3_1_8/CreateDomesticScheduledPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/scheduled/payments/consents/junit/v3_1_9/CreateDomesticScheduledPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/api/v3_1_8/CreateDomesticStandingOrderConsents.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/junit/v3_1_8/CreateDomesticStandingOrderConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/standing/order/consents/junit/v3_1_9/CreateDomesticStandingOrderConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/api/v3_1_8/CreateInternationalPaymentsConsents.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/api/v3_1_8/GetInternationalPaymentsConsentFundsConfirmation.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_8/CreateInternationalPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_8/GetInternationalPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_9/CreateInternationalPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_9/GetInternationalPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/legacy/LegacyGetInternationalPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/api/v3_1_8/CreateInternationalScheduledPayment.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/api/v3_1_8/CreateInternationalScheduledPaymentsConsents.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_8/CreateInternationalScheduledPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_8/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_9/CreateInternationalScheduledPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_9/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/legacy/LegacyGetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/505
Added functional tests for:
- Rejected consents in every type of payment
- Invalid status when making a funds confirmation request with an intent with the Consumed status.
From the [OB documentation](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/international-payment-consents.html#get-international-payment-consents-consentid-funds-confirmation):
An ASPSP can only respond to a funds confirmation request if the payment consent (international payment, international scheduled payment) resource has an Authorised status. If the status is not Authorised, an ASPSP must respond with a 400 (Bad Request) and a UK.OBIE.Resource.InvalidConsentStatus error code.
> 505: Add tests for Rejected and Consumed status intents

- codefresh.yml
The JUnit test report is produced by the gradle tests tasks, in this change the report is copied to the sbat-functional-test-reports GCP bucket.
Tests will be stored in a subfolder per day, then identified by the codefresh build_id.
An example report can be downloaded using the following command: `gsutil -m cp -r gs://sbat-functional-test-reports/20220914/6321fe0ddc5faa3f6b9efa37 .`
Reports for both successful and failed test runs will be stored. For failed runs, the slack notification message has been updated to include the gsutil command to download the report.
The bucket is configured to delete reports after 30 days.
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/513
> 513: Copying JUnit test reports to a GCP bucket

- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_8/GetDomesticPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_8/GetInternationalPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_8/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/337 
Description: Added the functional tests for the grant type verifier filter that were initially disabled as a future enhancement.
The functional tests for both international payment consents funds confirmation & international scheduled payment consents funds confirmation are being ignored as not implemented yet.
> 337: Adding functional tests for grant type verifier

- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_10/GetDomesticPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/payments/consents/junit/v3_1_9/GetDomesticPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_10/GetInternationalPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/payments/consents/junit/v3_1_9/GetInternationalPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_10/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_9/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/337
Description: Added v3_1_9 & v3_1_10 functional tests for the grant type verifier filter that were initially disabled as a future enhancement.
The functional tests for both international payment consents funds confirmation & international scheduled payment consents funds confirmation are being ignored as not implemented yet.
> Adding v3_1_9 & v3_1_10 functional tests for grant type verifier

- src/test/kotlin/com/forgerock/uk/openbanking/support/account/AccountRS.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/access/consents/AccountAccessConsentApi.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/account/access/consents/api/v3_1_8/AccountAccessConsent.kt
DELETE account access consent must return HTTP 204 No Content response
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/537
> 537: Fixing test for delete account access consent to match OB spec behaviour

- build.gradle.kts
- src/test/kotlin/com/forgerock/uk/openbanking/support/payment/OBJsonPaymentModel.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentApiClient.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentFactory.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/file/payments/consents/api/v3_1_8/CreateFilePaymentsConsents.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/file/payments/consents/api/v3_1_8/GetFilePaymentsConsents.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/file/payments/consents/junit/v3_1_10/CreateFilePaymentConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/file/payments/consents/junit/v3_1_10/GetFilePaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/file/payments/consents/junit/v3_1_8/CreateFilePaymentConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/file/payments/consents/junit/v3_1_8/GetFilePaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/file/payments/consents/junit/v3_1_9/CreateFilePaymentConsentsTest.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/file/payments/consents/junit/v3_1_9/GetFilePaymentsConsentsTest.kt
- src/test/resources/com/forgerock/securebanking/payment/file/UK_OBIE_PaymentInitiation_3_1.json
- src/test/resources/com/forgerock/securebanking/payment/file/UK_OBIE_pain_001_001_08.xml
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/562
Description: Added file payment consents functional tests including the ones for the new SubmitFile API (supporting both XML & JSON content-types).
> 562: Adding file payment consent tests

- src/test/kotlin/com/forgerock/securebanking/framework/data/RequestParameters.kt
FAPI conformance requires the nbf claim to be include in the /authorize request JWT
Issue: https://github.com/secureapigateway/secureapigateway/issues/676
> 676: Include nbf claim in authorise request jwt

- .github/workflows/pr.yml
Fix for codefresh changes for allowing github actions to call pipelines
Issue : https://github.com/SecureApiGateway/SecureApiGateway/issues/706
> 706 Fix github actions calling codefresh pipelines

- build.gradle.kts
By default, gradle caches the outputs of tasks. If the inputs do not change then when the task is run again the result is returning from the cache.
For test tasks, this means that the tests do not get re-run. To trigger a re-run the clean task must also be supplied, this slows the process down as the code needs to be recompiled
As our tests are integration tests, and are dependent upon an external environment, then caching the results does not make sense.
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/536
> 536: Disabling Gradle test task output caching

- src/test/kotlin/com/forgerock/uk/openbanking/framework/errors/Errors.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/junit/v3_1_10/CreateDomesticVrpTest.kt
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/736
Description: Added the functional test for "allow only sweeping vrp type".
> 736: Allow only sweeping vrp type functional test coverage

- gradle/profiles/profile-dev.gradle.kts
- gradle/profiles/profile-devops.gradle.kts
- gradle/profiles/profile-nightly.gradle.kts
- src/test/kotlin/com/forgerock/securebanking/framework/configuration/Config.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/account/AccountAS.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/general/GeneralAS.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/payment/PaymentAS.kt
- Using IG_SERVER configuration to build RCS API URLs
- Removing RCS_SERVER configuration as it is now redundant
- Updating RCS API calls to supply the AM cookie for authentication purposes
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/805
> 805: Calling RCS API via IG route

- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/api/v3_1_10/GetDomesticVrpDetails.kt
- src/test/kotlin/com/forgerock/uk/openbanking/tests/functional/payment/domestic/vrp/junit/v3_1_10/GetDomesticVrpDetailsTest.kt
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/758
Fixed details query to use domesticVRPId instead of consentId and added a test that submits a payment twice and gets the details for each of the payments.
> Functional tests updates for multiple domestic vrps

- gradle/profiles/profile-dev.gradle.kts
- src/test/kotlin/com/forgerock/securebanking/framework/configuration/Config.kt
- src/test/kotlin/com/forgerock/uk/openbanking/support/discovery/RsDiscovery.kt
IG_SERVER has moved from obdemo subdomain to sapig subdomain
Adding MTLS_SERVER config, this is on the mtls subdomain of the gateway domain.
Using MTLS_SERVER config when doing RS discovery. All calls to RS must use mtls, the discovery doc will then return mtls urls for the tests to use.
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/839
> 839: Using new sapig and mtls.sapig domains

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v3_1_8/GetDomesticPaymentsConsentFundsConfirmation.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/api/v3_1_10/GetDomesticVrpConsentsFundsConfirmation.kt
Asserting that the Domestic Payment and Domestic VRP Payment funds confirmation response contains valid self link.
https://github.com/SecureApiGateway/SecureApiGateway/issues/874
> 874: Testing Funds Confirmation response self links

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/CreateDomesticPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/CreateDomesticScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/api/v3_1_8/CreateDomesticStandingOrder.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/file/payments/api/v3_1_8/CreateFilePayment.kt
Adding an assertion to tests which create Payments to validate the the self link in the OB response object is valid.
https://github.com/SecureApiGateway/SecureApiGateway/issues/874
> 874: Testing Payments Self Links are valid

- gradle/profiles/profile-ob-sandbox-v1.gradle.kts
This profile is used to run the tests against the relenv v1 environment (sapig.ob-sandbox-v1.forgerock.financial)
https://github.com/SecureApiGateway/SecureApiGateway/issues/907
> 907: Adding ob-sandbox-v1 profile

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/errors/Errors.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/CreateDomesticPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/junit/v3_1_10/CreateDomesticPaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/CreateDomesticScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/junit/v3_1_10/CreateDomesticScheduledPaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/api/v3_1_8/CreateDomesticStandingOrder.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/junit/v3_1_10/CreateDomesticStandingOrderTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v3_1_10/CreateDomesticVrpTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/junit/v3_1_10/CreateInternationalPaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v3_1_8/CreateInternationalScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/api/v3_1_8/GetInternationalScheduledPaymentsConsentFundsConfirmation.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/junit/v3_1_10/CreateInternationalScheduledPaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/api/v3_1_8/CreateInternationalStandingOrder.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/junit/v3_1_10/CreateInternationalStandingOrderTest.kt
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/575
Description:
- Fixed tests that had the risk object missing or had the risk object mismatching between consent request and submit payment request.
- Added Risk validation functional tests support.
> 575: Adding functional tests support for Risk validation

- build.gradle.kts
And set versions to 0.9.1
Issue: https://github.com/secureapigateway/secureapigateway/issues/932
> 932: Prepare for release 0.9.1

- build.gradle.kts
- Updated version and release in build.gradle.kts descriptor file
- Use v1.0.0 of the common-bom
Issue: https://github.com/secureapigateway/secureapigateway/issues/927
> 927: Updated artifact version

- src/test/kotlin/com/forgerock/sapi/gateway/framework/data/Tpp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/PaymentApiClient.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/registration/Registration.kt
Found while trying to work out why nightly was failing tests (because of the issue 940)
Issue: https://github.com/secureapigateway/secureapigateway/issues/940
> 940: Tpps not being unregistered by functional tests

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/PaymentApiClient.kt
When a call to the SAPIG fails we now output the x-fapi-interaction-id value so that a failing request can be correlated with the logs of the SAPIG under test. 
Issue: https://github.com/secureapigateway/secureapigateway/issues/960
> 960: Output x-fapi-interaction-id if call fails

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/CreateDomesticPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/CreateDomesticScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/api/v3_1_8/CreateDomesticStandingOrder.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v3_1_8/CreateInternationalScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/api/v3_1_8/CreateInternationalStandingOrder.kt
- Improve current negative test to validate initiation
Issue: https://github.com/secureapigateway/secureapigateway/issues/955
> 955: initiation consent section match with initiation payment section

- build.gradle.kts
- src/test/kotlin/com/forgerock/sapi/gateway/framework/http/fuel/FuelInitialiser.kt
- Bumped commons 1.0.2
- Updated version to 1.0.2
- Updated Fuel initialiser to normalize the deserialiser and serialiser of date times 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/969
> 969: prepare SAPIG release 1.0.1

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v3_1_10/CreateDomesticVrpTest.kt
Adding test CreateDomesticVrpTest.shouldFailToCreateVrpWhenMaxIndividualAmountBreachedTest_v3_1_10
This test asserts that an error is returned when attempting to create a VRP payment with an instructed payment amount > maxIndividualAmount control param
https://github.com/SecureApiGateway/SecureApiGateway/issues/983
> 983: Adding VRP Test to check that payments fail if the maxIndividualAmount control param is breached

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/CreateDomesticPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/CreateDomesticScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/api/v3_1_8/CreateDomesticStandingOrder.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/consents/api/v3_1_8/CreateDomesticStandingOrderConsents.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v3_1_8/CreateInternationalScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/api/v3_1_8/CreateInternationalStandingOrder.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/consents/api/v3_1_8/CreateInternationalStandingOrderConsents.kt
Java Bean validation is now enabled in RS, this enforces schema validations based on the data-model annotations.
Fixing VRP tests to create payment requests which contain all mandatory fields.
Fixing negative tests to use test data that passes schema validation, then triggers biz logic errors
https://github.com/SecureApiGateway/SecureApiGateway/issues/578
> 578: Fixing test data to be compatible with OBIE schema validation rules

- build.gradle.kts
- Updated version to 1.0.4
- Bumped commons version 1.0.5
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1040
> 1040: prepare version to build the API-G release 1.0.3

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/framework/errors/Errors.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/CreateDomesticPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/GetDomesticPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v3_1_8/CreateDomesticPaymentsConsents.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/junit/v3_1_10/CreateDomesticPaymentConsentsTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/api/v3_1_8/CreateInternationalPaymentsConsents.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/junit/v3_1_10/CreateInternationalPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/junit/v3_1_8/CreateInternationalPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/junit/v3_1_9/CreateInternationalPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/api/v3_1_8/CreateInternationalScheduledPaymentsConsents.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_10/CreateInternationalScheduledPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_8/CreateInternationalScheduledPaymentsConsentsTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_9/CreateInternationalScheduledPaymentsConsentsTest.kt
- Changes to Error messages
- No longer validating that Domestic Payment Consents include charges, as RS impl does not generate any
- Disabling test: createDomesticPaymentsConsents_withNonExistentDebtorAccount_v3_1_10
- The logic is covered in the RCS when a Payment request is made, if the ResourceOwner does not own the account then the payment fails
- Raised https://github.com/SecureApiGateway/SecureApiGateway/issues/1041 to review / impl this logic if we want it at a later date
- Fixing International/International Scheduled Payment Idempotency tests which were calling the Domestic API by mistake
https://github.com/SecureApiGateway/SecureApiGateway/issues/1012
> 1012: Fixing tests to work with RCS Consent Store

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/account/access/consents/api/v3_1_8/AccountAccessConsent.kt
RS impl of AccountAccessConsentApi produces different errors to the IG impl, fixing error code and message assertion to work with the new format.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1035
> 1035: Fixing Consent not found error code and message assertion

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/junit/v3_1_10/CreateDomesticPaymentConsentsTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/api/v3_1_10/CreateDomesticVrpConsents.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/junit/v3_1_10/CreateDomesticVrpConsentsTest.kt
Disabling createDomesticVrpConsents_throwsInvalidDebtorAccount_v3_1_10 as this logic has not been implemented. See issue 1041
https://github.com/SecureApiGateway/SecureApiGateway/issues/1050
> 1050: Fixing idempotency error message

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/GetDomesticVrp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v3_1_10/GetDomesticVrpTest.kt
https://github.com/SecureApiGateway/SecureApiGateway/issues/1057
> 1057: Adding tests to validate VRP refund account is set correctly when requested

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v3_1_8/GetDomesticPaymentsConsentFundsConfirmation.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/junit/v3_1_10/GetDomesticPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/api/v3_1_10/CreateDomesticVrpConsentsFundsConfirmation.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/consents/junit/v3_1_10/CreateDomesticVrpConsentsFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/api/v3_1_8/GetInternationalPaymentsConsentFundsConfirmation.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/junit/v3_1_10/GetInternationalPaymentsConsentFundsConfirmationTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/api/v3_1_8/GetInternationalScheduledPaymentsConsentFundsConfirmation.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/junit/v3_1_10/GetInternationalScheduledPaymentsConsentFundsConfirmationTest.kt
Tests for: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/413
https://github.com/SecureApiGateway/SecureApiGateway/issues/1052
> 1052: Testing that funds confirmation requests fail when requested consentId is not authorised for the access_token provided

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/discovery/RsDiscovery.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/GetDomesticVrp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/GetDomesticVrpDetails.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v3_1_10/CreateDomesticVrpTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v3_1_10/GetDomesticVrpDetailsTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v3_1_10/GetDomesticVrpTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/junit/v3_1_10/GetInternationalScheduledPaymentDetailsTest.kt
The VRP payment operations names have been updated to use names consistent with the consent operations.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1075
> 1075: Updating VRP payment operation names

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/CreateDomesticPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/junit/v3_1_10/CreateDomesticPaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/CreateDomesticScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/junit/v3_1_10/CreateDomesticScheduledPaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/api/v3_1_8/CreateDomesticStandingOrder.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/junit/v3_1_10/CreateDomesticStandingOrderTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/api/v3_1_10/CreateDomesticVrp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/vrp/junit/v3_1_10/CreateDomesticVrpTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/file/payments/api/v3_1_8/CreateFilePayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/file/payments/junit/v3_1_10/CreateFilePaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/junit/v3_1_10/CreateInternationalPaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v3_1_8/CreateInternationalScheduledPayment.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/junit/v3_1_10/CreateInternationalScheduledPaymentTest.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/api/v3_1_8/CreateInternationalStandingOrder.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/junit/v3_1_10/CreateInternationalStandingOrderTest.kt
Adding a test to each payment type to verify that submission is idempotent when a duplicate request is submitted (with same x-idempotency-key and body)
https://github.com/SecureApiGateway/SecureApiGateway/issues/958
> 958: Testing payment submission idempotency

- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/file/payments/consents/api/v3_1_8/CreateFilePaymentsConsents.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/file/payments/consents/junit/v3_1_10/CreateFilePaymentConsentsTest.kt
Verify that creating a File Payment Consent for an unsupported fileType returns the appropriate error.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1095
> 1095: File Payment Consent test for unsupported fileType

- build.gradle.kts
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/event/EventNotificationRS.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/event/EventsDataFactory.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/events/aggregatedpolling/api/v3_1_10/AggregatedPolling.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/events/aggregatedpolling/junit/v3_1_10/AggregatedPollingTest.kt
- Bumped commons bom version 2.0.3
- Added rs store datamodel 2.0.2 as new dependency
- Added aggregated polling functional test coverage (poll, acknowledge, poll and acknowledge)
- Added gradle events test task for v3.1.10
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1001
> 1001: aggregated polling test coverage

- gradle/profiles/profile-dev.gradle.kts
- gradle/profiles/profile-devops.gradle.kts
- gradle/profiles/profile-fritss-itssdev.gradle.kts
- gradle/profiles/profile-nightly.gradle.kts
- gradle/profiles/profile-ob-sandbox-v1.gradle.kts
- gradle/profiles/profile-ob-sandbox-v2.gradle.kts
- src/test/kotlin/com/forgerock/sapi/gateway/framework/configuration/Config.kt
- src/test/kotlin/com/forgerock/sapi/gateway/framework/data/DynamicRegistration.kt
- src/test/kotlin/com/forgerock/sapi/gateway/framework/data/Tpp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/general/GeneralAS.kt
Changes applied to support tls_client_auth
- Adding clientAuthMethod configuration option to control the auth method used, defaulting this to private_key_jwt
- Adding eidasOBWacSubjectDN configuration which is required when doing tls_client_auth.
- Updating TPP DCR to support choosing the auth method based on the config
- Updating access_token requests to supply the client credentials using the configured auth method.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1134
> 1134: Supporting tls_client_auth token_endpoint_auth_method

- gradle/profiles/profile-dev.gradle.kts
- gradle/profiles/profile-devops.gradle.kts
- gradle/profiles/profile-fritss-itssdev.gradle.kts
- gradle/profiles/profile-nightly.gradle.kts
- gradle/profiles/profile-ob-sandbox-v1.gradle.kts
- gradle/profiles/profile-ob-sandbox-v2.gradle.kts
- src/test/kotlin/com/forgerock/sapi/gateway/framework/configuration/Config.kt
- src/test/kotlin/com/forgerock/sapi/gateway/framework/data/DynamicRegistration.kt
- src/test/kotlin/com/forgerock/sapi/gateway/framework/data/Tpp.kt
- src/test/kotlin/com/forgerock/sapi/gateway/ob/uk/support/registration/Registration.kt
eidasOBWacSubjectDN configuration has been removed in favour of extracting the value from the TPP's OBWac cert, this makes the config simpler and removes the possibility of misconfiguration.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1134
> 1134: Removing eidasOBWacSubjectDN config

- build.gradle.kts
- Updated version to 2.1.0
- Bumped common version 2.1.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1148
> 1148: prepare release 2.1.0

- build.gradle.kts
- Updated commons and project version to 2.2.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1182
> Prepare release 2.2.0

- src/main/kotlin/com/forgerock/sapi/gateway/framework/http/fuel/FuelInitialiser.kt
- Added LocalDate serializer in custom simple module in core
- Added LocalDate deserializer in custom simple module in core
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1175
Customer info defines the field BirthDate as LocalDate type, so that needs to be parsed with a specific serialiser / Deserialiser for LocalDate types to be formatted properly and avoid jackson invalid format errors when jackson parse the customer info object from the response.
The serialiser and deserialiser has been implemented and they live in Common project [here](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-common/tree/master/secure-api-gateway-ob-uk-common-obie-datamodel/src/main/java/uk/org/openbanking/jackson)
```java
// FuelInitialiser.kt#L80
val serializers: SimpleModule …
```
> 1175 add localDate serializer and deserializer to core

- .github/workflows/master.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- Makefile
- Change any pipelines to push to the new Artifact Registry
- Change any pipelines / packages that pull images to use the new Artifact Registry
- Change Auth to GCP pipeline command to use V2 as V0 is deprecated
Issue:
- https://github.com/SecureApiGateway/SecureApiGateway/issues/987
- https://github.com/SecureApiGateway/SecureApiGateway/issues/1202
> 987: Artifact Registry Migration

- src/main/kotlin/com/forgerock/sapi/gateway/framework/configuration/Config.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/account/AccountAS.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/funds/FundsConfirmationAS.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/general/GeneralAS.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/PaymentAS.kt
Spring Boot 3 is not mapping URIs with trailing slashes to the controller, the trailing slash is incorrect and should be removed.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1245
> 1245: Removing trailing slash from RCS Decision API calls

- build.gradle.kts
Remove release variable as can only see it being used once in the repo for setting a name of a file, which can be done with the version var
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1262
> 1262: Investigate duplicate version in Functional Test

- src/main/kotlin/com/forgerock/sapi/gateway/framework/signature/SignatureUtils.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/payment/JwsSignatureProducer.kt
There are a few places where we apply a 10 second negative skew to our iat values in jwts. This hid the issue described in 1358. This PR removes those skew values and exposes this issue in our SAPIG deployments.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1358
> 1358: Remove inbuilt skew from the functional tests

- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/support/funds/FundsConfirmationConsentFactory.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/api/v3_1_8/CreateDomesticPayment.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/payments/consents/api/v3_1_8/CreateDomesticPaymentsConsents.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/api/v3_1_8/CreateDomesticScheduledPayment.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/scheduled/payments/consents/api/v3_1_8/CreateDomesticScheduledPaymentsConsents.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/api/v3_1_8/CreateDomesticStandingOrder.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/domestic/standing/order/consents/api/v3_1_8/CreateDomesticStandingOrderConsents.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/file/payments/consents/api/v3_1_8/CreateFilePaymentsConsents.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/api/v3_1_8/CreateInternationalPayment.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/payments/consents/api/v3_1_8/CreateInternationalPaymentsConsents.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/api/v3_1_8/CreateInternationalScheduledPayment.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/scheduled/payments/consents/api/v3_1_8/CreateInternationalScheduledPaymentsConsents.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/api/v3_1_8/CreateInternationalStandingOrder.kt
- src/main/kotlin/com/forgerock/sapi/gateway/ob/uk/tests/functional/payment/international/standing/orders/consents/api/v3_1_8/CreateInternationalStandingOrderConsents.kt
DebtorAccount.Name for non-VRP payment submissions is an optional field. No longer settings this field to reproduce the bug in the linked issue.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1479
> 1479: Stop setting DebtorAccount.Name for non-VRP payments

- build.gradle.kts
Bump Common to snapshot version
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1605
> 1605: Make sure dev branches are not using latest snapshots for artifacts

- src/main/kotlin/com/forgerock/sapi/gateway/framework/data/DynamicRegistration.kt
If pairwise is not available as subject_types_supported value in the as well known response for the deployment, then the DCR reqistration request will now use the first value from that array, which is supported.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1658
> 1658: Tests should work against non pairwise deployments

- build.gradle.kts
Bump fuel-jackson to next available version `2.2.3`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1718
> 1718: Fix outdated dependancy for OB Func Tests

- gradle/profiles/profile-ob-sandbox-v4.gradle.kts
- src/main/kotlin/com/forgerock/sapi/gateway/framework/configuration/Config.kt
Update KIDs so that new automated testing certificates can be used for V4 testing in release environment
A 4.0.5 image will be created for Functional Tests following this merge
Issue: https://pingidentity.atlassian.net/jira/software/c/projects/OPENIG/boards/1322?selectedIssue=OPENIG-9694
> OpenIG-9694: Update Signing and Transport KID for OB V4
